services:
  - type: web
    name: flask-onnx-app
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONPATH
        value: /opt/render/project/src
    disk:
      name: flask-app-disk
      mountPath: /opt/render/project/src
      sizeGB: 1